# 6.then 穿透实现

then 方法的 onFulfilled/onRejected 函数作为参数是可选的，如果没有提供处理函数，由最后一个 then 的函数处理。

```js
const enum STATUS { // 存放状态，ts枚举
  pending = 'PENDING',
  fulfilled = 'FULFILLED',
  rejected = 'REJECTED'
}

// 解析x的类型(第一个then的返回结果)，来决定promise2走成功还是失败
function resolvePromise(promise2, x, resolve, reject) {
  if (x === promise2) {
    return reject(new TypeError('类型出错'))
  }

  //兼容其他promise，返回的promise可以是对象和函数
  if ((typeof x === 'object' && x !== null) || typeof x === 'function') {
    let called = false; // 表示没调过成功和失败。加锁，防止状态的改变
    try {
      let then = x.then; // 取x上的then方法
      if (typeof then === 'function') { // 只要x上有then函数，就认为x是promise
        let y = then.call(x, y => {
          if (called) return;
          called = true;
          resolvePromise(promise2, y, resolve, reject); // y可能是一个promise，递归解析，直到是一个普通值为止
        }, r => {
          if (called) return;
          called = true;
          reject(r);
        });
      } else {
        resolve(x); // 普通对象{}
      }
    } catch (e) {
      if (called) return;
      called = true;
      reject(e);
    }
  } else {
    resolve(x); // 普通值
  }
}

class Promise {
  status: STATUS;
  value: any;
  reason: any;
  onResolvedCallback: Function[];
  onRejectedCallback: Function[];
  constructor(executor: (resolve: (value?: any) => void, reject: (reason?: any) => void) => void) {
    this.status = STATUS.pending; // 当前状态
    this.value = undefined; // 成功原因
    this.reason = undefined;  // 失败原因
    this.onResolvedCallback = [];
    this.onRejectedCallback = [];

    const resolve = (value?: any) => { // 调resolve更改status状态，并把传入的value保存下来。加？表示value允许不传参
      if (this.status === STATUS.pending) { // 只有等待态时才允许修改状态和值，否则不生效
        this.status = STATUS.fulfilled;
        this.value = value;
        this.onResolvedCallback.forEach(fn => fn());
      }
    }
    const reject = (reason?: any) => { // 逻辑和resolve类似
      if (this.status === STATUS.pending) {
        this.status = STATUS.rejected;
        this.reason = reason;
        this.onRejectedCallback.forEach(fn => fn());
      }
    }

    try { // 如果promise初始执行报错，也走reject状态
      executor(resolve, reject)
    } catch (e) {
      reject(e)
    }
  }
  then(onFulfilled?, onRejected?) {
    onFulfilled = typeof onFulfilled === 'function' ? onFulfilled : val => val; // onFulfilled参数可选
    onRejected = typeof onRejected === 'function' ? onRejected : err => { throw err };
    let promise2 = new Promise((resolve, reject) => { // 为了实现链式调用的效果，返回一个新的promise
      if (this.status == STATUS.fulfilled) {
        setTimeout(() => {  // 需要先产生promise2。这里加一个setTimeout，让里面的代码异步执行
          try {
            let x = onFulfilled(this.value);
            resolvePromise(promise2, x, resolve, reject);
          } catch (e) {
            reject(e);
          }
        }, 0);
      }
      if (this.status == STATUS.rejected) {
        setTimeout(() => {
          try {
            let x = onRejected(this.reason); // 这里x是普通值
            resolvePromise(promise2, x, resolve, reject);
          } catch (e) {
            reject(e);
          }
        }, 0);
      }
      if (this.status == STATUS.pending) { //如果executor()有异步代码，执行then时还是等待态，就把成功回调和失败回调存起来
        this.onResolvedCallback.push(() => { // 切片编程，套一层函数
          setTimeout(() => {
            try {
              let x = onFulfilled(this.value);
              resolvePromise(promise2, x, resolve, reject);
            } catch (e) {
              reject(e);
            }
          }, 0);
        })
        this.onRejectedCallback.push(() => {
          setTimeout(() => {
            try {
              let x = onRejected(this.reason); // 这里x是普通值
              resolvePromise(promise2, x, resolve, reject);
            } catch (e) {
              reject(e);
            }
          }, 0);
        })
      }
    });
    return promise2;
  }
}

export default Promise;
```

##### 测试代码

```js
const Promise = require('./bundle');

let p = new Promise((resolve, reject) => {
  resolve('data1'); // => success data1
  // reject('err1'); // => faild2 err1
});

p.then()
  .then()
  .then(
    data => {
      console.log('success', data);
    },
    err => {
      console.log('faild2', err);
    },
  );
```

总结：

onFulfilled 没有参数时默认是`val => val`，把成功值传递给下一个 then

onRejected 没有参数时默认是`err => { throw err }`，把失败值抛出，下一个 then 会拦截到
