# 8.拓展-Promise.all 等静态方法

ES6 的`promise`除了`PromiseA+规范`，还添加了一些常用的功能，比如`Promise.all`，`Promise.resolve`，`Promise.reject`等

## 8.1 支持 resolve 返回 promise

`PromiseA+规范`只支持`onFulfilled/onRejected`返回 promise，实际业务中有可能会有`resolve`返回`promise`的需求

##### 思路：

> 1.如果`resolve`的`value`值是一个`Promise`的实例，则解析`promise`的结果，并用`resolve/reject`去处理接收解析的结果；
>
> 2.如果是`resolve`不用去解析`promise`的结果

```js
class Promise {
  const resolve = (value?: any) => { // 调resolve更改status状态，并把传入的value保存下来。加？表示value允许不传参
      if(value instanceof Promise){ // 支持resolve promise，递归解析
        return value.then(resolve, reject);
      }
      if (this.status === STATUS.pending) { // 只有等待态时才允许修改状态和值，否则不生效
        this.status = STATUS.fulfilled;
        this.value = value;
        this.onResolvedCallback.forEach(fn => fn());
      }
    }
}

export default Promise;
```

##### 测试代码

```js
const Promise = require('./bundle');

let p = new Promise((resolve, reject) => {
  // resolve(...)
  resolve(
    new Promise((resolve, reject) => {
      setTimeout(() => {
        resolve('ok');
      }, 1000);
    }),
  );
});

p.then(data => {
  console.log('success', data);
});

// success ok
```

## 8.2 catch 实现

`catch`是实例方法（`Promise.prototype.catch`）。`promise`允许`then`不写错误处理函数，统一由最后的`catch`捕获。

##### 思路：

> `catch`其实就是不带`onFulfilled`的`then`方法。因为`onRejected`不写的情况下，是有抛给一下`then`的，报错信息一直没有丢失。

```js
class Promise {
  then(onFulfilled?, onRejected?) {
    // 省略代码...
  }
  catch(errFn) {
    return this.then(null, errFn);
  }
}

export default Promise;
```

##### 测试代码

```js
const Promise = require('./bundle');

let p = new Promise((resolve, reject) => {
  reject('err1'); // => faild2 err1
});

p.then(data => {
  console.log('success', data);
}).catch(err => {
  console.log('faild2', err);
});

// faild2 err1
```

## 8.3 Promise.resolve 和 Promise.reject 实现

`Promise.resolve`和`Promise.reject`是类是静态方法。

##### 思路：

> 1.`Promise.resolve`返回一个新的`promise`，用`resolve`去接传入的值，传递给下一个`then`。如果传入的是`promise`，则会递归解析
>
> 2.`Promise.reject`返回一个新的`promise`，把错误传递下一个`then`。如果传入的是`promise`，不会去解析`promise`里面的值

```js
class Promise {
  then(onFulfilled?, onRejected?) {
    // 省略代码...
  }
  catch(errFn) {
    // 省略代码...
  }
  static resolve(value) {
    return new Promise((resolve, reject) => {
      resolve(value);
    });
  }
  static reject(reason) {
    return new Promise((resolve, reject) => {
      reject(reason);
    });
  }
}

export default Promise;
```

##### 测试代码

```js
const Promise = require('./bundle');

Promise.resolve('ok').then(data => {
  console.log('success', data);
});
// success ok

// ----------------------------------------- //

Promise.reject('err').then(null, err => {
  console.log('faild2', err);
});
// faild2 err

Promise.reject(
  new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve('ok');
    }, 1000);
  }),
).then(null, err => {
  console.log('faild2', err);
});
// faild2 Promise{}
```

## 8.4 Promise.all 实现

`Promise.all`是类的静态方法，允许传入一个数组，里面有多个异步任务，所有异步任务成功后一起返回结果并回调函数。如果有一个异步任务失败了，则全部失败。

##### 思路：

> 1.`Promise.all`调用后接的是`then`，那肯定返回的是一个新`promise`。
>
> 2.在里面循环执行异步任务，收集结果。
>
> 3.如果是普通值，直接保存；如果是`promise`，解析结果后保存，解析出是拒绝态，直接`reject`整个`promise`
>
> 4.用计数器统计全部任务是否完成，完成则`resolve`返回结果

```js
class Promise {
  static resolve(value) {
    // 省略代码...
  }
  static reject(reason) {
    // 省略代码...
  }
  static all(values) {
    const isPromise = value => {
      // 判断传入值是否为promise
      if (
        (typeof value === 'object' && value !== null) ||
        typeof value === 'function'
      ) {
        if (typeof value.then === 'function') {
          return true;
        }
      }
      return false;
    };

    return new Promise((resolve, reject) => {
      // Promise.all返回的是一个新promise
      const arr = [];
      let times = 0;
      const collect = (value, key) => {
        arr[key] = value;
        if (++times === values.length) {
          // 不能用arr.length==values.length,有可能最后一项先返回填充进去
          resolve(arr);
        }
      };

      for (let i = 0; i < values.length; i++) {
        const value = values[i];
        if (isPromise(value)) {
          value.then(
            y => {
              collect(y, i);
            },
            e => {
              // 简写reject
              reject(e);
            },
          );
        } else {
          collect(value, i);
        }
      }
    });
  }
}

export default Promise;
```

##### 测试代码

```js
const Promise = require('./bundle');

const p1 = new Promise((resolve, reject) => {
  // 第一个1秒的异步任务
  setTimeout(() => {
    resolve('1秒');
  }, 1000);
});
const p2 = new Promise((resolve, reject) => {
  // 第二个2秒的异步任务
  setTimeout(() => {
    resolve('2秒');
  }, 2000);
});

Promise.all([p1, p2, 4, 5]).then(data => {
  console.log(data);
});
// [ '1秒', '2秒', 4, 5 ]
```

## 8.5 finally 实现

`finally`是实例方法。1.不管前一个`promise`解析后是成功或者失败，`finally`的回调都会执行。如果`finally`返回的是`promise`且解析为失败，会用`finally`的失败

##### 思路：

> 1.finally 接的是 then，所以返回的也是一个 promise
>
> 2.finally 的回调执行后可能返回一个 promise，所以用 Promise.resolve 包裹 callback()，才能等待 promise 执行，用 then 去解析结果。
>
> 3.如果 finally 回调返回成功态，忽略，返回上一个 then 的成功值；如果 finally 回调返回失败态，忽略，返回上一个 then 的失败值，因为 finally 回调的失败值已经先抛出去了

```js
class Promise {
  then(onFulfilled?, onRejected?) {
    // 省略代码...
  }
  catch(errFn) {
    // 省略代码...
  }
  finally(callback) {
    return this.then(
      data => {
        return Promise.resolve(callback()).then(() => data); // finally回调返回普通值(成功)，是不会传递到下一个then的
      },
      err => {
        // 前一个失败，finally成功，也会返回失败。finally失败会默认抛出错误，先用finally的失败
        return Promise.resolve(callback()).then(() => {
          throw err;
        });
      },
    );
  }
}

export default Promise;
```

##### 测试代码

```js
const Promise = require('./bundle');

const p = new Promise((resolve, reject) => {
  setTimeout(() => {
    // resolve('ok1')
    reject('err1');
  }, 50);
});

p.finally(() => {
  console.log('finally');
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      // resolve('ok2')
      reject('err2');
    }, 500);
  });
}).then(
  data => {
    console.log('success', data);
  },
  err => {
    console.log('faild', err);
  },
);

// finally
// faild err2
```

## 拓展后的完整代码

[Promise-ts 环境和代码](https://github.com/zwhid/example/tree/master/JavaScript/promise/promise-ts)

```js
const enum STATUS { // 存放状态，ts枚举
  pending = 'PENDING',
  fulfilled = 'FULFILLED',
  rejected = 'REJECTED'
}

// 解析x的类型(第一个then的返回结果)，来决定promise2走成功还是失败
function resolvePromise(promise2, x, resolve, reject) {
  if (x === promise2) {
    return reject(new TypeError('类型出错'))
  }

  //兼容其他promise，返回的promise可以是对象和函数
  if ((typeof x === 'object' && x !== null) || typeof x === 'function') {
    let called = false; // 表示没调过成功和失败。加锁，防止状态的改变
    try {
      let then = x.then; // 取x上的then方法
      if (typeof then === 'function') { // 只要x上有then函数，就认为x是promise
        let y = then.call(x, y => {
          if (called) return;
          called = true;
          resolvePromise(promise2, y, resolve, reject); // y可能是一个promise，递归解析，直到是一个普通值为止
        }, r => {
          if (called) return;
          called = true;
          reject(r);
        });
      } else {
        resolve(x); // 普通对象{}
      }
    } catch (e) {
      if (called) return;
      called = true;
      reject(e);
    }
  } else {
    resolve(x); // 普通值
  }
}

class Promise {
  status: STATUS;
  value: any;
  reason: any;
  onResolvedCallback: Function[];
  onRejectedCallback: Function[];
  constructor(executor: (resolve: (value?: any) => void, reject: (reason?: any) => void) => void) {
    this.status = STATUS.pending; // 当前状态
    this.value = undefined; // 成功原因
    this.reason = undefined;  // 失败原因
    this.onResolvedCallback = [];
    this.onRejectedCallback = [];

    const resolve = (value?: any) => { // 调resolve更改status状态，并把传入的value保存下来。加？表示value允许不传参
      if (value instanceof Promise) { // 支持resolve promise，递归解析
        return value.then(resolve, reject);
      }
      if (this.status === STATUS.pending) { // 只有等待态时才允许修改状态和值，否则不生效
        this.status = STATUS.fulfilled;
        this.value = value;
        this.onResolvedCallback.forEach(fn => fn());
      }
    }
    const reject = (reason?: any) => { // 逻辑和resolve类似
      if (this.status === STATUS.pending) {
        this.status = STATUS.rejected;
        this.reason = reason;
        this.onRejectedCallback.forEach(fn => fn());
      }
    }

    try { // 如果promise初始执行报错，也走reject状态
      executor(resolve, reject)
    } catch (e) {
      reject(e)
    }
  }
  then(onFulfilled?, onRejected?) {
    onFulfilled = typeof onFulfilled === 'function' ? onFulfilled : val => val;
    onRejected = typeof onRejected === 'function' ? onRejected : err => { throw err };
    let promise2 = new Promise((resolve, reject) => { // 为了实现链式调用的效果，返回一个新的promise
      if (this.status == STATUS.fulfilled) {
        setTimeout(() => {  // 需要先产生promise2。这里加一个setTimeout，让里面的代码异步执行
          try {
            let x = onFulfilled(this.value);
            resolvePromise(promise2, x, resolve, reject);
          } catch (e) {
            reject(e);
          }
        }, 0);
      }
      if (this.status == STATUS.rejected) {
        setTimeout(() => {
          try {
            let x = onRejected(this.reason); // 这里x是普通值
            resolvePromise(promise2, x, resolve, reject);
          } catch (e) {
            reject(e);
          }
        }, 0);
      }
      if (this.status == STATUS.pending) { //如果executor()有异步代码，执行then时还是等待态，就把成功回调和失败回调存起来
        this.onResolvedCallback.push(() => { // 切片编程，套一层函数
          setTimeout(() => {
            try {
              let x = onFulfilled(this.value);
              resolvePromise(promise2, x, resolve, reject);
            } catch (e) {
              reject(e);
            }
          }, 0);
        })
        this.onRejectedCallback.push(() => {
          setTimeout(() => {
            try {
              let x = onRejected(this.reason); // 这里x是普通值
              resolvePromise(promise2, x, resolve, reject);
            } catch (e) {
              reject(e);
            }
          }, 0);
        })
      }
    });
    return promise2;
  }
  catch(errFn) {
    return this.then(null, errFn);
  }
  finally(callback) {
    return this.then(data => {
      return Promise.resolve(callback()).then(() => data); // finally回调返回普通值(成功)，是不会传递到下一个then的
    }, err => {
      // 前一个失败，finally成功，也会返回失败。finally失败会默认抛出错误，先用finally的失败
      return Promise.resolve(callback()).then(() => { throw err });
    })
  }
  static resolve(value) {
    return new Promise((resolve, reject) => {
      resolve(value);
    })
  }
  static reject(reason) {
    return new Promise((resolve, reject) => {
      reject(reason);
    })
  }
  static all(values) {
    const isPromise = (value) => { // 判断传入值是否为promise
      if ((typeof value === 'object' && value !== null) || typeof value === 'function') {
        if (typeof value.then === 'function') {
          return true;
        }
      }
      return false;
    }

    return new Promise((resolve, reject) => { // Promise.all返回的是一个新promise
      const arr = [];
      let times = 0;
      const collect = (value, key) => {
        arr[key] = value;
        if (++times === values.length) {
          resolve(arr);
        }
      }

      for (let i = 0; i < values.length; i++) {
        const value = values[i];
        if (isPromise(value)) {
          value.then(y => {
            collect(y, i);
          }, e => { // 简写reject
            reject(e)
          })
        } else {
          collect(value, i);
        }
      }
    })
  }
}

export default Promise;
```
